services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TrafficTickets
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend
    depends_on:
      - postgres


  discovery:
    build:
      context: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8091:8091"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev, native
      DATABASE_URL: 'jdbc:postgresql://postgres:5432/TrafficTickets'
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  authorization:
    build:
      context: ./authorization
    container_name: authorization
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      discovery:
        condition: service_started
      config-server:
        condition: service_started
    ports:
      - "8060:8060"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: 'jdbc:postgresql://postgres:5432/TrafficTickets'
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      TOKEN-SIGNING-KEY: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8060/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tickets:
    build:
      context: ./tickets
    container_name: tickets
    restart: on-failure
    ports:
      - "8010:8010"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: 'jdbc:postgresql://postgres:5432/TrafficTickets'
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
      discovery:
        condition: service_started

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: {}
  postgres: {}
  tickets: {}
  discovery: {}
  config-server: {}
  gateway: {}
  pgadmin_data: {}
