spring:
  application:
    name: pin
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/TrafficTickets'
    username: postgres
    password: admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:image/src/main/resources/static/

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true

eureka:
  instance:
    hostname: discovery
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port:
    8010

